import type { MaterialProperties } from "@/types/database";

export const DEFAULT_MATERIAL_PROPS: Required<MaterialProperties> = {
  albedoMapUrl:       null,
  normalMapUrl:       null,
  normalScale:        1,
  bumpMapUrl:         null,
  bumpScale:          0.05,
  roughnessMapUrl:    null,
  glossinessMapUrl:   null,
  metalnessMapUrl:    null,
  aoMapUrl:           null,
  aoIntensity:        1,
  displacementMapUrl: null,
  displacementScale:  0.05,
  emissiveColor:      "#000000",
  emissiveIntensity:  0,
  opacity:            1,
  uvProjection:       "uv",
  uvScale:            1,
  uvScaleX:           1,
  uvScaleY:           1,
  uvScaleZ:           1,
  uvTriOffsetX:       0,
  uvTriOffsetY:       0,
  uvTriOffsetZ:       0,
  uvTriRotation:      0,
  uvRepeatX:          1,
  uvRepeatY:          1,
  uvOffsetX:          0,
  uvOffsetY:          0,
  uvRotation:         0,
  colorTint:          false,
  albedoBrightness:   1,
  ior:                1.5,
  clearcoat:          0,
  clearcoatRoughness: 0,
  transmission:       0,
};
